# NUMPY

## Numpy is a general purpose array-processing package in python

In [2]:
import numpy as np

In [3]:
#1d array from a python list
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [5]:
#2d array from a nested python list
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array attributes

In [7]:
#shape
shape = arr2d.shape
print(shape)

(2, 3)


In [8]:
zeros_arr.shape

(3, 4)

In [9]:
#size
size = arr2d.size
print(size)

6


In [10]:
zeros_arr.size

12

In [ ]:
#data type
data_type = arr2d.dtype
print(data_type)

int64


In [11]:
zeros_arr.dtype

dtype('float64')

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


## Array Operations

In [12]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#addition
addition = 2 + arr2d
print(addition)

[[3 4 5]
 [6 7 8]]


In [ ]:
#subtraction
subtraction = arr2d - 3
print(subtraction)

[[-2 -1  0]
 [ 1  2  3]]


In [ ]:
#Multiplication
multiplication = 4 * arr2d
print(multiplication)

[[ 4  8 12]
 [16 20 24]]


## Aggregation Functions

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#sum
total_sum = arr2d.sum()
print(total_sum)

21


In [ ]:
#max
max_val = arr2d.max()
print(max_val)

6


In [ ]:
#min
min_val = arr2d.min()
print(min_val)

1


## Indexing

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#second row
second_row = arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [ ]:
#first row
first_row = arr2d[0:1,:]
print(first_row)

[[1 2 3]]


In [ ]:

second_row_element = arr2d[1:,1:]
print(second_row_element)

[[5 6]]


In [ ]:
first_row_element = arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [ ]:
first_row_ = arr2d[0:1,1:]
print(first_row_)

[[2 3]]


In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


In [ ]:
first_row_ = arr2d[:1,1:]
print(first_row_)

[[2 3]]


In [ ]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


## Array Manipulation

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [15]:
arr2d.shape

(2, 3)

In [ ]:
#reshape
reshaped_arr = arr2d.reshape(3,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
reshaped_arr1 = arr2d.reshape(1,6)
print(reshaped_arr1)

[[1 2 3 4 5 6]]


In [16]:
#Concatenate Arrays
arr1d = [1,2,3]
concat_arr = np.concat([arr1d,arr1d])
print(concat_arr)

[1 2 3 1 2 3]


In [ ]:
#Concatenate Arrays 2
arr1d = np.array([1,2,3])
concat_arr2 = np.concatenate([arr1d,np.array([4,5,6])])
print(concat_arr2)

[1 2 3 4 5 6]


In [ ]:
#append
arr1d = np.array([1,2,3])
append_arr = np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [ ]:
#append to 2 dimensional array
arr2d = np.array([[1,2,3],[4,5,6]])
append_arr1 = np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Question asked

### Can you append a row ([4,5,6]) to the array [1,2,3], so it looks like this [[1,2,3],[4,5,6]] rather than this: [1,2,3,4,5,6]?

### Answer: To achieve that, both arrays need to be two-dimensional arrays.

In [ ]:
#Answer to question asked
arr1d = np.array([[1,2,3]])
concat_arr2 = np.concatenate([arr1d,np.array([[4,5,6]])])
print(concat_arr2)

[[1 2 3]
 [4 5 6]]


## Broadcasting

In [ ]:
#broadcasting
a = np.array([1,2,3])
b = 4
print(a+b)

[5 6 7]


In [ ]:
a = np.array([1,2,3])
b = 6
print(a*b)

[ 6 12 18]


In [ ]:
a = np.array([1,2,3])
print(4 + a)

[5 6 7]


## Random Number Generation

In [4]:
random_numbers = np.random.rand(3,3)
print(random_numbers)

[[0.63050886 0.93021621 0.65627035]
 [0.06751862 0.82117589 0.59659237]
 [0.40141616 0.8962833  0.33494547]]


In [5]:
random_numbers = np.random.rand(4,6)
print(random_numbers)

[[0.45469584 0.69181887 0.33371348 0.43336744 0.03608319 0.86452522]
 [0.04810509 0.21581101 0.59320357 0.44011856 0.60657496 0.55824657]
 [0.76182252 0.3365759  0.70417767 0.13109903 0.84030422 0.52695524]
 [0.41983335 0.96304093 0.97501305 0.05073541 0.75182197 0.12031108]]


In [6]:
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[77 13 44 73 98 64]


In [7]:
random_numbers_ = np.random.randint(0,100,6).reshape(3,2)
print(random_numbers_)

[[94 58]
 [67 46]
 [48 73]]


In [9]:
random_numbers1 = np.random.randn(4, 7)
print(random_numbers1)

[[ 0.30950902  0.24931656  0.36687902  2.35216416  1.31958376 -0.10210708
   1.00863229]
 [-0.155419    0.8626189   0.32557332  0.15858378  0.93354093 -1.86523471
  -1.52949197]
 [-0.22326748  0.29380875  0.68970999  0.37195318  1.023907   -0.21354186
   1.05875403]
 [ 0.06704179 -1.1843462  -0.01619702  0.12486079  0.54031952 -0.48149668
  -0.50272714]]


In [12]:
items = np.array (["A", "B", "C", "D"])
items

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [13]:
random_numbers2 = np.random.choice(items, 3)
print(random_numbers2)

['A' 'D' 'D']


## Linear Algebra

In [19]:
# Matrix Addition
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [16]:
A

array([[1, 2],
       [3, 4]])

In [17]:
B

array([[5, 6],
       [7, 8]])

In [15]:
print(A + B)

[[ 6  8]
 [10 12]]


In [ ]:
#Matrix Subtraction
print(A - B)

[[-4 -4]
 [-4 -4]]


In [20]:
#Matrix Multiplication (Element-wise multiplication)
print(A * B)

[[ 5 12]
 [21 32]]


In [21]:
#Matrix Multiplication
print(A @ B)

[[19 22]
 [43 50]]


In [22]:
result = np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
#Normal Matrix Multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [ ]:
#Matrix Multiplication (Column-wise)
print(A * B)

[[ 5 12]
 [21 32]]


In [ ]:
# Standard Matrix multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [23]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
#Transpose of a matrix
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [ ]:
#Transpose of a matrix
transpose_B = np.transpose(B)
print(transpose_B)

[[5 7]
 [6 8]]


In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#Inverse of a matrix
B_inv = np.linalg.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [ ]:
#identity Matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
B

array([[5, 6],
       [7, 8]])

In [29]:
#determinant of a matrix
determinant = np.linalg.det(B)
print(int(determinant))

-2


## Delete elements in an array

In [ ]:
arr = np.array([1,2,3,4,5])
arr_deleted = np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [ ]:
arr_deleted = np.delete(arr,4)
print(arr_deleted)

[1 2 3 4]


In [ ]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
print(arr_deleted)

['Madrid' 'Dortmund' 'PSG' 'Mancity']


In [ ]:
arr = np.array([1,2,3,4,5])
m = arr != 5
new_arr = arr[m]
print(new_arr)

[1 2 3 4]


### To make sure that the elements that are removed in arr_deleted are also deleted in club_arr

In [ ]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
club_arr = arr_deleted
print(club_arr)


['Madrid' 'Dortmund' 'PSG' 'Mancity']


## Statistical Functions

In [31]:
arr = np.array([1,2,3,4,5])


In [32]:
#mean
arr_mean = np.mean(arr)
print(arr_mean)

3.0


In [ ]:
#median
arr_median = np.median(arr)
print(arr_median)

3.0


In [34]:
arr_1 = np.array([1,2,3,4,5,6])

In [35]:
arr1_median = np.median(arr_1)
print(arr1_median)

3.5


In [38]:
#Mode : numpy does not have the mode method, so scipy can be used
arr_ = np.array([1,2,2,3,4,5,6])
from scipy import stats
arr_mode = stats.mode(arr_,keepdims = False)
print(arr_mode)

ModeResult(mode=np.int64(2), count=np.int64(2))


In [ ]:
#standard deviation
arr_std = np.std(arr)
print(arr_std)

1.4142135623730951
